//
//  SnakeData.swift
//  Assignment One (iOS)
//
//  Created by Le Helen on 24/07/2022.
//

import Foundation

var snakes: [Snake] = [
    Snake(name: "Black Mamba", description: "The black mamba is a species of highly venomous snake. It is the second-longest venomous snake after the king cobra. In a threat display, the black mamba usually opens its inky-black mouth, spreads its narrow neck-flap and sometimes hisses.", secondDescription: " It is capable of striking at considerable range and may deliver a series of bites in rapid succession. Its venom is primarily composed of neurotoxins that often induce symptoms within ten minutes, and is frequently fatal unless antivenom is administered.", shortDescription: "Their bite is known as the 'Kiss of Death'.", location: "Sub-Saharan Africa",status: "Least Concern", statusEmoji: "🎊",tag: ["venomous"], imageName: "black-mamba"),
    Snake(name: "King Cobra", description: "The king cobra is a venomous snake species of elapids endemic to jungles in Southern and Southeast Asia. It is distinguishable from other cobras, most noticeably by its size and neck patterns. The king cobra is the world's longest venomous snake.", secondDescription: "When provoked, it is capable of striking a target at long range and well above the ground. Rather than biting and retreating, it may sustain its bite and inject a large quantity of venom, which is a medical emergency.", shortDescription: "They are the only snake that builds nests for its eggs.", location: "Southern and Southeast Asia", status: "Threatened", statusEmoji: "🚩", tag: ["venomous"], imageName: "king-cobra"),
    Snake(name: "Belcher's sea snake", description: "Belcher's sea snake is an extremely venomous sea snake. It has a timid temperament and would normally have to be subjected to severe mistreatment before biting. Usually those bitten are fishermen handling nets, although only one-quarter of those bitten are envenomated since the snake rarely injects much of its venom.", secondDescription: "Its diet consists of a variety of fish and shellfish.It breathes air, and has valves over its nostrils that close underwater. It can hold its breath for as long as 7 to 8 hours while hunting and even sleeping, but then has to surface for a quick breath of air.", shortDescription: "Two milligrams of its venom can kill a thousand people.", location: "Tropical reefs of the Indian Ocean", status: "Unknown", statusEmoji: "❓", tag: ["venomous"], imageName: "belcher"),
    
    Snake(name: "Texas diamond-back Rattlesnake", description: "The Texas diamond-back is a venomous rattlesnake species and member of the Viper family, found in the southwestern United States and Mexico. It is likely responsible for the majority of snakebite fatalities in northern Mexico and the greatest number of snakebites in the U.S.", secondDescription: "94.8% of their prey consisted of small mammals.They hunt (or ambush prey) at night or in the early morning. These snakes can go for up to two years without food in the wild. They are one of the few species of snakes that engage in scavenging behavior.", shortDescription: "The babies are on their own to find food as soon as they're born.", location: "Southwestern United States and Mexico", status: "Least Concern", statusEmoji: "🎊", tag: ["venomous"], imageName: "diamond-back-rattlesnake"),
    
    Snake(name: "Egg-eating Snake", description: "Egg-eating snakes are a recognized group of snakes belonging to two different genera (scientific groups). These genera are Dasypeltis and Elachistodon. They are non-venomous and have adapted to live in locations with lots of birds. These snakes are some of the most adept climbers in the world, which allows them to scale rocks and trees with ease.", secondDescription: "Their sense of smell allows them to tell if an egg is too far developed to eat or if it is rotten, all without having to break it open. Egg-eaters don’t have any teeth, allowing them to swallow the egg without any hangups. When they are scared, they rub their scales against one another to create a hissing sound, hoping to scare off predators.", shortDescription: "Egg-eating snakes eat their eggs whole, internally crush them, and regurgitate the shells.", location: "India, Africa and Bangladesh", status: "Least Concern", statusEmoji: "🎊", tag: ["non-venomous"], imageName: "egg-eating-snake"),
    
    Snake(name: "Inland Taipan", description: "The venom of the inland taipan is by far the most toxic of any snake – much more so than even that of sea snakes.", secondDescription: "Unlike other venomous snakes that strike with a single, accurate bite then retreat while waiting for the prey to die, the fierce snake subdues the prey with a series of rapid, accurate strikes. It is known to deliver up to eight venomous bites in a single attack,often snapping its jaws fiercely several times to inflict multiple punctures in the same attack.", shortDescription: "They have evolved specifically to kill mammals.", location: "Australia", status: "Least Concern", statusEmoji: "🎊", tag: ["venomous"], imageName: "inland-taipan"),
]
